# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'FacebookDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'FBAudienceNetwork', '~> 4.10.1'
  # Pods for FacebookDemo

  target 'FacebookDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FacebookDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
